
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.coding.net/CoderJH/LionFMSpecs.git'

platform :ios, '8.0'

target 'LionFM' do
    use_frameworks!
    
    
    pod 'LionFMMain'

#pod 'LionFMBase/Category'
#pod 'LionFMBase/Base'
#pod 'LionFMBase/Tool'
#pod 'LionFMBase/Network'
#pod 'MJExtension'

end
